### ISSUE TITLE
XQW.stripGuid broken in version 4.3.1

### ISSUE THREAD

**Issue by strwase** [delegateas/XrmDefinitelyTyped#108] opened 2019-05-09 11:39 UTC
XQW.stripGuid doesn't clear the parentheses from a guid field.
the endswith part of the function returns false when it should return true.
making the function just return the original string instead of the stripped version.

![image](https://user-images.githubusercontent.com/10077785/57450894-04889e80-7260-11e9-9383-3cb7d66f9eea.png)

**Comment by altmank** [comment] 2019-05-14 18:53
I think that is caused by this commit:
https://github.com/delegateas/XrmDefinitelyTyped/commit/495f54e00bf8542fe46ce9d372bdf8ea44426ea4#r33534979

**Comment by magesoe** [comment] 2019-05-24 09:03
Fixed in version 4.3.2

**Closed as completed by magesoe** 2019-05-24 09:03 UTC
