### ISSUE TITLE
Support for formContext.ui.quickForms

### ISSUE THREAD

**Issue by zunin** [delegateas/XrmDefinitelyTyped#164] opened 2020-02-05 14:47 UTC
It would be great if XrmDefinitelyTypes supported this as well!

The client api is at https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-quickforms

**Comment by henrikhannemose** [comment] 2020-02-05 14:57
I definitely agree. This is a sought-after feature. PRs are very welcome :)

**Comment by henrikhannemose** [comment] 2020-02-05 14:57
Duplicate of #12

**Comment by zunin** [comment] 2020-02-06 08:49
closed as duplicate

**Closed as completed** 2020-02-06 08:49 UTC
