### ISSUE TITLE
Problem with upgrading XrmDefinetelyTyped nuget

### ISSUE THREAD

**Issue by jaroslawrutk** [delegateas/XrmDefinitelyTyped#204] opened 2021-01-27 18:55 UTC
My team is facing problem with updating nuget because this is changing a lot of files in project and we need to refactor +100 js files and test this after all.

What we want:
We need the latest version of typings in xrm.d.ts file because CRM for now have problem with 'openWebResource' method but NavigateTo is working well (tested via js). We have deprecated old version of XrmDefinetelyTyped (2.6.1) after update there is a lot of changes in declarations of methods. That changes have impact on already wrote code.

![image](https://user-images.githubusercontent.com/28161292/106039489-77dbdf00-60d9-11eb-8cc2-00063c867114.png)

**Environment**
- D365
- Tool version: [2.6.1]
- .Net Framework 4.5.2

**Comment by magesoe** [comment] 2021-03-05 08:25
The jump from 2.6.1 and onwards is the jump from pre v9 typings to post v9 typings. If you don't know, Microsoft made a lot of changes here, some of which are still only deprecated due to being a big change. My recommendation is to bite the apple, stop generating deprecated typings and do things the right way. 

If I am mistaken and your environment is not v9 or above, then please correct me, but if I am right then you have had 2 years to update these deprecations.

**Comment by misoeli** [comment] 2021-06-11 10:48
Assuming the previous assumption is right, the issue is resolved "just" by updating, as mentioned. Thus, closing.

**Closed as completed by misoeli** 2021-06-11 10:48 UTC
