### ISSUE TITLE
Missing tabs in generated typings

### ISSUE THREAD

**Issue by hansgfixed** [delegateas/XrmDefinitelyTyped#116] opened 2019-06-13 13:30 UTC
Hello everybody

When generating definition files of some forms the dts files are missing tabs and sections while others contain them.

Example:

```
interface Tabs extends Xrm.TabCollectionBase {
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
```

Any idea what could be the issue? Customizations have been all published and not just once to rule out this case. 

Thanks in advance

**Comment by magesoe** [comment] 2019-06-13 13:33
Which entities are missing the tabs? Any common theme among them?

**Comment by hansgfixed** [comment] 2019-06-13 14:00
Hi magesoe,
thanks for the prompt reply.

Totally forgot to mention the context. They are custom entities and neither the tab nor the section are declared in the generated dts file. On the other hand the webresource inside the said tab and section is declared correctly as Xrm.WebResourceControl in the controls interface. 

I've now checked another form which contains a webresource and the corresponding dts file is also missing the tab declaration in which this webresource is located but contains all other tabs and sections.

**Comment by hansgfixed** [comment] 2019-06-13 14:08
I've an example:

Email.dts

`namespace Tabs {
      interface Email extends Xrm.SectionCollectionBase {
        get(name: "Email_section_6"): Xrm.PageSection;
        get(name: "Regarding information"): Xrm.PageSection;
        get(name: "attachments"): Xrm.PageSection;
        get(name: "email description"): Xrm.PageSection;
        get(name: "recipient information"): Xrm.PageSection;
        get(name: "tab_4_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_administration extends Xrm.SectionCollectionBase {
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: "tab_administration_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }`

`interface Tabs extends Xrm.TabCollectionBase {
      get(name: "Email"): Xrm.PageTab<Tabs.Email>;
      get(name: "tab_administration"): Xrm.PageTab<Tabs.tab_administration>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }`

The tab is called "tab_3" and the section "tab_3_section_1" on the form which is missing in the dts.

**Comment by hansgfixed** [comment] 2019-06-19 06:02
Issue has been resolved. The solution was to remove the brackets in the tab naming. So there is no issue with webresources inside tabs when generating declaration files. Tested this case too.

![grafik](https://user-images.githubusercontent.com/44840416/59752124-0ba0c480-9282-11e9-9917-c5cce4e927a4.png)

Case closed. 👍 

Update: I recalled another project in which tab names with brackets were declared though in v.4.0.2 while I'm now running v4.3.10.

**Comment by magesoe** [comment] 2019-06-21 06:02
Glad you found a solution, I will leave this issue open until I have looked into any differences between the versions. 
Why don't you name your tabs something meaningful?

**Comment by hansgfixed** [comment] 2019-06-21 07:12
> Why don't you name your tabs something meaningful?

Seperate customizers and developers. Changed all such occurences to something meaningful after I tried with removing the brackets.

**Comment by magesoe** [comment] 2019-06-21 13:40
I couldn't reproduce the bug in 4.3.10, used the same name and label as you. I'll close the issue. If the error occurs again I would like a solution with the form

**Closed as completed by magesoe** 2019-06-21 13:40 UTC
