### ISSUE TITLE
Datetime attributes are not included in Declaration files Is it just datetimefields?

### ISSUE THREAD

**Issue by D365Guy** [delegateas/XrmDefinitelyTyped#4] opened 2017-05-22 10:19 UTC
I have form with Seven attributes on them.  I have published my customisations.
![not all attributes added to declaration files](https://cloud.githubusercontent.com/assets/28806385/26303081/e1c2248a-3ed5-11e7-85d4-ac7878104863.PNG)
UPRN: Of type string
Status: Of type Status 
Status Reason: Status Reason
X CoOrdinate: Decimal
Y CoOrdinate: Decimal
Start Date: Datetime
End Date: Datetime

Here is the attributes interface taken from Information.d.ts for Main form of blpu
Here you'll see that StartDate and End Date is missing also the Statecode and statusreason codes are also missing but referenced from a different def file.

```typescript
declare namespace Form.hive_blpu.Main {
  namespace Information {
    namespace Tabs {
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "hive_uprn"): Xrm.Attribute<string>;
      get(name: "hive_x_coordinate"): Xrm.NumberAttribute;
      get(name: "hive_y_coordinate"): Xrm.NumberAttribute;
      get(name: string): Xrm.EmptyAttribute;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
```

Can you look into this please as we have many other forms with multiple attributes which has the same problem and this is blocking us from continuing

![not all attributes added to declaration files2](https://cloud.githubusercontent.com/assets/28806385/26303775/50dbd3b4-3ed8-11e7-8bc4-9d2cf755f2c1.PNG)

Thanks

[Edit: added code formatting]

**Comment by mktange** [comment] 2017-05-22 11:46
I am not able to reproduce this error on either CRM 2016 Update 1 or D365.

Which version of CRM are you experiencing this in?

**Comment by D365Guy** [comment] 2017-05-22 12:07
Hi Martin,
My bad, I have an Incorrect connection to an old instance.  Apologies

Cheers

Lloyd

**Comment by mktange** [comment] 2017-05-22 12:12
Alright, closing the issue then.

**Closed as completed by mktange** 2017-05-22 12:12 UTC
